"""add pipeline coordination and failure diagnoses

Revision ID: 1a1a1f44b125
Revises: 95064db3600f
Create Date: 2026-10-02 15:30:17.170454

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a1a1f44b125"
down_revision: str | Sequence[str] | None = "95064db3600f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment_diagnoses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("deployment_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by", sa.BigInteger(), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "TIMED_OUT",
                name="diagnosis_job_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("model_selection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("deployment_context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_logs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployment_requests.id"],
            name=op.f("fk_deployment_diagnoses_deployment_id_deployment_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_deployment_diagnoses_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_deployment_diagnoses_service_id_services"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_diagnoses")),
        sa.UniqueConstraint("deployment_id", "attempt_id", name="uq_deployment_diagnoses_attempt"),
    )
    op.create_index(
        "ix_deployment_diagnoses_latest",
        "deployment_diagnoses",
        ["deployment_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_deployment_diagnoses_queue",
        "deployment_diagnoses",
        ["status", "locked_until"],
        unique=False,
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("service_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by", sa.BigInteger(), nullable=False),
        sa.Column("source_repository_url", sa.String(length=500), nullable=False),
        sa.Column("source_branch", sa.String(length=255), nullable=False),
        sa.Column("source_sha", sa.String(length=40), nullable=False),
        sa.Column("root_directory", sa.String(length=255), nullable=False),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "MANUAL",
                "PUSH",
                "CLI",
                "REDEPLOY",
                "ROLLBACK",
                name="deployment_trigger",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("auto_deploy", sa.Boolean(), nullable=False),
        sa.Column("enable_auto_deploy", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "ANALYZING",
                "AWAITING_INPUT",
                "PLANNING",
                "BUILDING",
                "DEPLOYING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="pipeline_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=True),
        sa.Column("deployment_request_id", sa.BigInteger(), nullable=True),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confirmed_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deployment_dossier", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("planning_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("execution_plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("plan_digest", sa.String(length=64), nullable=True),
        sa.Column("model_selection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["service_analyses.id"],
            name=op.f("fk_pipeline_runs_analysis_id_service_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["deployment_request_id"],
            ["deployment_requests.id"],
            name=op.f("fk_pipeline_runs_deployment_request_id_deployment_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_pipeline_runs_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_pipeline_runs_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_pipeline_runs_idempotency_key")),
    )
    op.create_index(
        "ix_pipeline_runs_latest",
        "pipeline_runs",
        ["service_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_pipeline_runs_queue", "pipeline_runs", ["status", "locked_until"], unique=False
    )
    op.create_index(
        "uq_pipeline_runs_active",
        "pipeline_runs",
        ["service_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('ANALYZING','AWAITING_INPUT','PLANNING','BUILDING','DEPLOYING')"
        ),
    )
    op.add_column("builds", sa.Column("source_sha", sa.String(length=64), nullable=True))
    op.add_column("builds", sa.Column("source_archive_digest", sa.String(length=80), nullable=True))
    op.add_column("builds", sa.Column("source_snapshot_key", sa.Text(), nullable=True))
    op.add_column(
        "builds", sa.Column("build_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("releases", sa.Column("image_repository", sa.String(length=500), nullable=True))
    op.add_column("releases", sa.Column("revert_commit_sha", sa.String(length=64), nullable=True))
    op.add_column("releases", sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("releases", "deadline_at")
    op.drop_column("releases", "revert_commit_sha")
    op.drop_column("releases", "image_repository")
    op.drop_column("builds", "build_config")
    op.drop_column("builds", "source_snapshot_key")
    op.drop_column("builds", "source_archive_digest")
    op.drop_column("builds", "source_sha")
    op.drop_index(
        "uq_pipeline_runs_active",
        table_name="pipeline_runs",
        postgresql_where=sa.text(
            "status IN ('ANALYZING','AWAITING_INPUT','PLANNING','BUILDING','DEPLOYING')"
        ),
    )
    op.drop_index("ix_pipeline_runs_queue", table_name="pipeline_runs")
    op.drop_index("ix_pipeline_runs_latest", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index("ix_deployment_diagnoses_queue", table_name="deployment_diagnoses")
    op.drop_index("ix_deployment_diagnoses_latest", table_name="deployment_diagnoses")
    op.drop_table("deployment_diagnoses")
    # ### end Alembic commands ###
