"""create build tables

Revision ID: cf3b3859224c
Revises:
Create Date: 2026-10-01 20:25:31.506816

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf3b3859224c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_user_id", name=op.f("uq_users_github_user_id")),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("github_repository_id", sa.BigInteger(), nullable=False),
        sa.Column("repository_full_name", sa.String(), nullable=False),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=True),
        sa.Column("root_directory", sa.String(), server_default=".", nullable=False),
        sa.Column(
            "builder",
            sa.Enum("auto", "dockerfile", "railpack", name="builder", native_enum=False, length=32),
            server_default="auto",
            nullable=False,
        ),
        sa.Column("dockerfile_path", sa.String(), nullable=True),
        sa.Column("auto_deploy", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_services_owner_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("slug", name=op.f("uq_services_slug")),
    )
    op.create_index(
        op.f("ix_services_github_repository_id"), "services", ["github_repository_id"], unique=False
    )
    op.create_index(op.f("ix_services_owner_user_id"), "services", ["owner_user_id"], unique=False)
    op.create_table(
        "deployment_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("prod", name="environment", native_enum=False, length=32),
            server_default="prod",
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("MANUAL", "PUSH", name="deploymenttrigger", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("source_sha", sa.String(), nullable=True),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("requested_by", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "INITIALIZING",
                "BUILDING",
                "DEPLOYING",
                "SUCCEEDED",
                "FAILED",
                "ROLLED_BACK",
                "MANUAL_INTERVENTION",
                "SUPERSEDED",
                name="deploymentstatus",
                native_enum=False,
                length=32,
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column(
            "failure_code",
            sa.Enum(
                "SOURCE_NOT_ACCESSIBLE",
                "SOURCE_REF_NOT_FOUND",
                "SOURCE_TOO_LARGE",
                "BUILD_CONFIG_REQUIRED",
                "BUILD_FAILED",
                "BUILD_TIMED_OUT",
                "BUILD_INFRA_ERROR",
                "DEPLOY_FAILED",
                name="failurecode",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_deployment_requests_requested_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_deployment_requests_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_requests")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_deployment_requests_idempotency_key")),
    )
    op.create_index(
        op.f("ix_deployment_requests_service_id"),
        "deployment_requests",
        ["service_id"],
        unique=False,
    )
    op.create_table(
        "builds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SNAPSHOTTING",
                "BUILDING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="buildstatus",
                native_enum=False,
                length=32,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "builder",
            sa.Enum("auto", "dockerfile", "railpack", name="builder", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("source_sha", sa.String(), nullable=True),
        sa.Column("codebuild_build_id", sa.String(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("image_repository", sa.String(), nullable=True),
        sa.Column("image_tag", sa.String(), nullable=True),
        sa.Column("image_digest", sa.String(), nullable=True),
        sa.Column("deploy_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "failure_code",
            sa.Enum(
                "SOURCE_NOT_ACCESSIBLE",
                "SOURCE_REF_NOT_FOUND",
                "SOURCE_TOO_LARGE",
                "BUILD_CONFIG_REQUIRED",
                "BUILD_FAILED",
                "BUILD_TIMED_OUT",
                "BUILD_INFRA_ERROR",
                "DEPLOY_FAILED",
                name="failurecode",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("log_url", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_request_id"],
            ["deployment_requests.id"],
            name=op.f("fk_builds_deployment_request_id_deployment_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_builds")),
        sa.UniqueConstraint("deployment_request_id", name=op.f("uq_builds_deployment_request_id")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "BUILD",
                "DEPLOY",
                "RECONCILE",
                "ROLLBACK",
                name="jobkind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "RETRY_WAIT",
                "FAILED",
                "MANUAL_INTERVENTION",
                name="jobstatus",
                native_enum=False,
                length=32,
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("locked_by", sa.String(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["deployment_request_id"],
            ["deployment_requests.id"],
            name=op.f("fk_jobs_deployment_request_id_deployment_requests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        op.f("ix_jobs_deployment_request_id"), "jobs", ["deployment_request_id"], unique=False
    )
    op.create_index("ix_jobs_status_run_after", "jobs", ["status", "run_after"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_status_run_after", table_name="jobs")
    op.drop_index(op.f("ix_jobs_deployment_request_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("builds")
    op.drop_index(op.f("ix_deployment_requests_service_id"), table_name="deployment_requests")
    op.drop_table("deployment_requests")
    op.drop_index(op.f("ix_services_owner_user_id"), table_name="services")
    op.drop_index(op.f("ix_services_github_repository_id"), table_name="services")
    op.drop_table("services")
    op.drop_table("users")
    # ### end Alembic commands ###
