"""create releases table

Revision ID: 499d60073fc0
Revises: cf3b3859224c
Create Date: 2026-10-01 22:57:08.330973

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "499d60073fc0"
down_revision: str | Sequence[str] | None = "cf3b3859224c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_request_id", sa.Integer(), nullable=False),
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("image_digest", sa.String(), nullable=False),
        sa.Column("gitops_commit_sha", sa.String(), nullable=True),
        sa.Column("revert_commit_sha", sa.String(), nullable=True),
        sa.Column("previous_good_release_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SUCCEEDED",
                "FAILED",
                "ROLLING_BACK",
                "ROLLED_BACK",
                name="releasestatus",
                native_enum=False,
                length=32,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "failure_code",
            sa.Enum(
                "SOURCE_NOT_ACCESSIBLE",
                "SOURCE_REF_NOT_FOUND",
                "SOURCE_TOO_LARGE",
                "BUILD_CONFIG_REQUIRED",
                "BUILD_FAILED",
                "BUILD_TIMED_OUT",
                "BUILD_INFRA_ERROR",
                "DEPLOY_FAILED",
                "DEPLOY_TIMED_OUT",
                "DEPLOY_INFRA_ERROR",
                name="failurecode",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"], ["builds.id"], name=op.f("fk_releases_build_id_builds")
        ),
        sa.ForeignKeyConstraint(
            ["deployment_request_id"],
            ["deployment_requests.id"],
            name=op.f("fk_releases_deployment_request_id_deployment_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_good_release_id"],
            ["releases.id"],
            name=op.f("fk_releases_previous_good_release_id_releases"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"], ["services.id"], name=op.f("fk_releases_service_id_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint(
            "deployment_request_id", name=op.f("uq_releases_deployment_request_id")
        ),
    )
    op.create_index(
        "ix_releases_service_id_status_id", "releases", ["service_id", "status", "id"], unique=False
    )
    op.create_index(
        "uq_releases_service_id_in_flight",
        "releases",
        ["service_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PENDING', 'ROLLING_BACK')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_releases_service_id_in_flight",
        table_name="releases",
        postgresql_where=sa.text("status IN ('PENDING', 'ROLLING_BACK')"),
    )
    op.drop_index("ix_releases_service_id_status_id", table_name="releases")
    op.drop_table("releases")
    # ### end Alembic commands ###
