-- 물리 DB 스키마(DDL) 단일 출처 — PostgreSQL.
-- app/models/*.py, alembic/versions/ 와 일치시킨다 (.claude/rules/db-migration.md).

CREATE TABLE github_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    installation_id BIGINT NOT NULL,
    account_login VARCHAR(255) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_github_installations PRIMARY KEY (id),
    CONSTRAINT uq_github_installations_installation_id UNIQUE (installation_id)
);

CREATE TABLE targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    region VARCHAR(32),
    domain_suffix VARCHAR(255),
    cluster_ref VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_targets PRIMARY KEY (id),
    CONSTRAINT ck_targets_target_kind CHECK (kind IN ('AWS', 'LOCAL')),
    CONSTRAINT uq_targets_name UNIQUE (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id BIGINT NOT NULL,
    login VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_github_id UNIQUE (github_id)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_owner_id_users FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE INDEX ix_projects_owner_id ON projects (owner_id);

CREATE UNIQUE INDEX uq_projects_owner_id_name ON projects (owner_id, name) WHERE NOT is_deleted;

CREATE TABLE user_github_installations (
    user_id BIGINT NOT NULL,
    github_installation_id BIGINT NOT NULL,
    CONSTRAINT pk_user_github_installations PRIMARY KEY (user_id, github_installation_id),
    CONSTRAINT fk_user_github_installations_github_installation_id_git_2fda FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_user_github_installations_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    github_installation_id BIGINT NOT NULL,
    source_branch VARCHAR(255) NOT NULL,
    root_directory VARCHAR(255),
    is_auto_deploy BOOLEAN DEFAULT true NOT NULL,
    builder VARCHAR(32),
    dockerfile_path VARCHAR(255),
    platform VARCHAR(32) DEFAULT 'linux/amd64' NOT NULL,
    railpack_version VARCHAR(32),
    analysis_plan JSONB,
    port INTEGER,
    build_command TEXT,
    start_command TEXT,
    scaling_config JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT ck_services_builder CHECK (builder IN ('dockerfile', 'railpack')),
    CONSTRAINT fk_services_github_installation_id_github_installations FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_services_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id)
);

CREATE INDEX ix_services_github_installation_id ON services (github_installation_id);

CREATE INDEX ix_services_project_id ON services (project_id);

CREATE UNIQUE INDEX uq_services_project_id_name ON services (project_id, name) WHERE NOT is_deleted;

CREATE TABLE service_targets (
    service_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    CONSTRAINT pk_service_targets PRIMARY KEY (service_id, target_id),
    CONSTRAINT fk_service_targets_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_targets_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id)
);

CREATE INDEX ix_service_targets_target_id ON service_targets (target_id);

CREATE TABLE service_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    service_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_uploads PRIMARY KEY (id),
    CONSTRAINT fk_service_uploads_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_uploads_uploaded_by_users FOREIGN KEY(uploaded_by) REFERENCES users (id),
    CONSTRAINT uq_service_uploads_public_id UNIQUE (public_id)
);

CREATE INDEX ix_service_uploads_expires_at ON service_uploads (expires_at);

CREATE TABLE deployment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    source_sha VARCHAR(64) NOT NULL,
    source_commit_message TEXT,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    requested_by BIGINT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    variables_snapshot JSONB,
    scaling_snapshot JSONB,
    source_deployment_request_id BIGINT,
    cancel_requested_at TIMESTAMP WITH TIME ZONE,
    service_upload_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_requests PRIMARY KEY (id),
    CONSTRAINT ck_deployment_requests_environment CHECK (environment IN ('prod')),
    CONSTRAINT ck_deployment_requests_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR')),
    CONSTRAINT ck_deployment_requests_deployment_status CHECK (status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT ck_deployment_requests_deployment_trigger CHECK (trigger_type IN ('MANUAL', 'PUSH', 'CLI', 'REDEPLOY', 'ROLLBACK', 'RESTART', 'REMOVE')),
    CONSTRAINT fk_deployment_requests_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT fk_deployment_requests_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_deployment_requests_service_upload_id_service_uploads FOREIGN KEY(service_upload_id) REFERENCES service_uploads (id),
    CONSTRAINT fk_deployment_requests_source_deployment_request_id FOREIGN KEY(source_deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT uq_deployment_requests_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_deployment_requests_service_upload_id UNIQUE (service_upload_id)
);

CREATE INDEX ix_deployment_requests_service_id_created_at ON deployment_requests (service_id, created_at);

CREATE UNIQUE INDEX uq_deployment_requests_active ON deployment_requests (service_id, environment) WHERE status IN ('QUEUED', 'BUILDING', 'DEPLOYING');

CREATE TABLE builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    builder VARCHAR(32),
    source_sha VARCHAR(64),
    codebuild_build_id VARCHAR(255),
    attempt INTEGER DEFAULT 1 NOT NULL,
    image_repository VARCHAR(500),
    image_tag VARCHAR(128),
    image_digest VARCHAR(80),
    deploy_config JSONB,
    failure_code VARCHAR(32),
    log_url TEXT,
    log_tail JSONB,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_builds PRIMARY KEY (id),
    CONSTRAINT ck_builds_build_status CHECK (status IN ('PENDING', 'SNAPSHOTTING', 'BUILDING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_builds_builder CHECK (builder IN ('dockerfile', 'railpack')),
    CONSTRAINT ck_builds_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR')),
    CONSTRAINT fk_builds_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT uq_builds_codebuild_build_id UNIQUE (codebuild_build_id),
    CONSTRAINT uq_builds_deployment_request_id UNIQUE (deployment_request_id)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    priority INTEGER DEFAULT 0 NOT NULL,
    run_after TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    attempts INTEGER DEFAULT 0 NOT NULL,
    max_attempts INTEGER DEFAULT 5 NOT NULL,
    locked_by VARCHAR(255),
    locked_until TIMESTAMP WITH TIME ZONE,
    external_id VARCHAR(255),
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT ck_jobs_job_kind CHECK (kind IN ('BUILD', 'DEPLOY', 'RECONCILE', 'ROLLBACK', 'REMOVE')),
    CONSTRAINT ck_jobs_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'RETRY_WAIT', 'FAILED', 'MANUAL_INTERVENTION')),
    CONSTRAINT fk_jobs_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id)
);

CREATE INDEX ix_jobs_deployment_request_id ON jobs (deployment_request_id);

CREATE INDEX ix_jobs_queued ON jobs (priority DESC, created_at) WHERE status = 'QUEUED';

-- Worker 깨우기: job 생성, RUNNING → QUEUED·RETRY_WAIT, BUILD 종료 때 commit 시점에 NOTIFY jobs, <kind>.
CREATE FUNCTION notify_job_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('jobs', NEW.kind);
    RETURN NULL;
END $$;

CREATE TRIGGER trg_jobs_notify_insert AFTER INSERT ON jobs
    FOR EACH ROW EXECUTE FUNCTION notify_job_change();

CREATE TRIGGER trg_jobs_notify_release AFTER UPDATE OF status ON jobs
    FOR EACH ROW WHEN (OLD.status = 'RUNNING'
        AND (NEW.status IN ('QUEUED', 'RETRY_WAIT') OR NEW.kind = 'BUILD'))
    EXECUTE FUNCTION notify_job_change();

CREATE TABLE releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    build_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    image_digest VARCHAR(80) NOT NULL,
    gitops_commit_sha VARCHAR(64),
    revert_commit_sha VARCHAR(64),
    argo_sync_status VARCHAR(32),
    argo_health_status VARCHAR(32),
    previous_good_release_id BIGINT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    deadline_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_releases PRIMARY KEY (id),
    CONSTRAINT ck_releases_environment CHECK (environment IN ('prod')),
    CONSTRAINT ck_releases_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR')),
    CONSTRAINT ck_releases_release_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'ROLLING_BACK', 'ROLLED_BACK')),
    CONSTRAINT fk_releases_build_id_builds FOREIGN KEY(build_id) REFERENCES builds (id),
    CONSTRAINT fk_releases_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_releases_previous_good_release_id_releases FOREIGN KEY(previous_good_release_id) REFERENCES releases (id),
    CONSTRAINT fk_releases_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_releases_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id)
);

CREATE INDEX ix_releases_deployment_request_id ON releases (deployment_request_id);

CREATE INDEX ix_releases_last_known_good ON releases (service_id, environment, target_id, status);

CREATE UNIQUE INDEX uq_releases_service_id_target_id_in_flight ON releases (service_id, target_id) WHERE status IN ('PENDING', 'ROLLING_BACK');

CREATE TABLE deployment_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_status_histories PRIMARY KEY (id),
    CONSTRAINT ck_deployment_status_histories_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR')),
    CONSTRAINT ck_deployment_status_histories_from_status CHECK (from_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT ck_deployment_status_histories_to_status CHECK (to_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT fk_deployment_status_histories_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id)
);

CREATE INDEX ix_deployment_status_histories_deployment_request_id_created_at ON deployment_status_histories (deployment_request_id, created_at);

CREATE TABLE service_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    key VARCHAR(128) NOT NULL,
    encrypted_value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_variables PRIMARY KEY (id),
    CONSTRAINT fk_service_variables_service_id_services FOREIGN KEY(service_id) REFERENCES services (id)
);

CREATE UNIQUE INDEX uq_service_variables_service_id_key ON service_variables (service_id, key);

CREATE TABLE cli_login_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    poll_secret_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    user_id BIGINT,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    last_polled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_cli_login_sessions PRIMARY KEY (id),
    CONSTRAINT ck_cli_login_sessions_cli_login_session_status CHECK (status IN ('PENDING', 'APPROVED', 'DENIED', 'EXPIRED')),
    CONSTRAINT fk_cli_login_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id),
    CONSTRAINT uq_cli_login_sessions_public_id UNIQUE (public_id)
);

CREATE INDEX ix_cli_login_sessions_expires_at ON cli_login_sessions (expires_at);

CREATE TABLE deployment_diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    requested_by BIGINT,
    status VARCHAR(32) NOT NULL,
    result JSONB,
    error_code VARCHAR(64),
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_diagnoses PRIMARY KEY (id),
    CONSTRAINT ck_deployment_diagnoses_diagnosis_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT fk_deployment_diagnoses_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_deployment_diagnoses_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id)
);

CREATE INDEX ix_deployment_diagnoses_deployment_request_id_created_at ON deployment_diagnoses (deployment_request_id, created_at);

CREATE UNIQUE INDEX uq_deployment_diagnoses_deployment_request_id_running ON deployment_diagnoses (deployment_request_id) WHERE status = 'RUNNING';
