-- 물리 DB 스키마(DDL) 단일 출처 — PostgreSQL.
-- app/models/*.py, alembic/versions/ 와 일치시킨다 (.claude/rules/db-migration.md).

CREATE TABLE github_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    installation_id BIGINT NOT NULL,
    account_login VARCHAR(255) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_github_installations PRIMARY KEY (id),
    CONSTRAINT uq_github_installations_installation_id UNIQUE (installation_id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id BIGINT NOT NULL,
    login VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_github_id UNIQUE (github_id)
);

CREATE TABLE targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    region VARCHAR(32),
    domain_suffix VARCHAR(255),
    cluster_ref VARCHAR(255),
    owner_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_targets PRIMARY KEY (id),
    CONSTRAINT ck_targets_target_kind CHECK (kind IN ('AWS', 'ONPREM', 'GCP')),
    CONSTRAINT fk_targets_owner_id_users FOREIGN KEY(owner_id) REFERENCES users (id),
    CONSTRAINT uq_targets_name UNIQUE (name)
);

CREATE INDEX ix_targets_owner_id ON targets (owner_id);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_owner_id_users FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE INDEX ix_projects_owner_id ON projects (owner_id);

CREATE UNIQUE INDEX uq_projects_owner_id_name ON projects (owner_id, name) WHERE NOT is_deleted;

CREATE TABLE user_github_installations (
    user_id BIGINT NOT NULL,
    github_installation_id BIGINT NOT NULL,
    CONSTRAINT pk_user_github_installations PRIMARY KEY (user_id, github_installation_id),
    CONSTRAINT fk_user_github_installations_github_installation_id_git_2fda FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_user_github_installations_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    github_installation_id BIGINT,
    source_branch VARCHAR(255) NOT NULL,
    root_directory VARCHAR(255),
    is_auto_deploy BOOLEAN DEFAULT true NOT NULL,
    builder VARCHAR(32),
    dockerfile_path VARCHAR(255),
    docker_target VARCHAR(128),
    platform VARCHAR(32) DEFAULT 'linux/amd64' NOT NULL,
    railpack_version VARCHAR(32),
    analysis_plan JSONB,
    port INTEGER,
    build_command TEXT,
    start_command TEXT,
    scaling_config JSONB,
    deployment_strategy VARCHAR(32) DEFAULT 'ROLLING' NOT NULL,
    -- APP(소스 빌드) · DATABASE(고정 공식 이미지 관리형 DB). DATABASE 는 github_installation_id 가 없고
    -- 저장소 주소·브랜치가 빈 문자열이다. database_config = {image, storageGi, port, user, database,
    -- initScripts?: [{name, path, kind, sha256, size}]} (initScripts 내용은 database_init_scripts).
    kind VARCHAR(32) DEFAULT 'APP' NOT NULL,
    database_engine VARCHAR(32),
    database_config JSONB,
    -- [{name, targetServiceId, port}] 서비스 namespace 의 ExternalName 별칭.
    host_aliases JSONB,
    stack_id BIGINT,
    stack_unit_id VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT ck_services_builder CHECK (builder IN ('dockerfile', 'railpack')),
    CONSTRAINT ck_services_deployment_strategy CHECK (deployment_strategy IN ('ROLLING', 'CANARY', 'BLUE_GREEN')),
    CONSTRAINT ck_services_service_kind CHECK (kind IN ('APP', 'DATABASE')),
    CONSTRAINT ck_services_database_engine CHECK (database_engine IN ('postgres', 'mysql', 'mongodb', 'redis')),
    CONSTRAINT fk_services_github_installation_id_github_installations FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_services_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id)
);

CREATE INDEX ix_services_github_installation_id ON services (github_installation_id);

CREATE INDEX ix_services_project_id ON services (project_id);

CREATE UNIQUE INDEX uq_services_project_id_name ON services (project_id, name) WHERE NOT is_deleted;

CREATE INDEX ix_services_stack_id ON services (stack_id);

CREATE UNIQUE INDEX uq_services_stack_id_stack_unit_id ON services (stack_id, stack_unit_id) WHERE stack_id IS NOT NULL AND NOT is_deleted;

CREATE TABLE service_targets (
    service_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    CONSTRAINT pk_service_targets PRIMARY KEY (service_id, target_id),
    CONSTRAINT fk_service_targets_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_targets_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id)
);

CREATE INDEX ix_service_targets_target_id ON service_targets (target_id);

CREATE TABLE service_uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    service_id BIGINT NOT NULL,
    uploaded_by BIGINT NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_uploads PRIMARY KEY (id),
    CONSTRAINT fk_service_uploads_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_uploads_uploaded_by_users FOREIGN KEY(uploaded_by) REFERENCES users (id),
    CONSTRAINT uq_service_uploads_public_id UNIQUE (public_id)
);

CREATE INDEX ix_service_uploads_expires_at ON service_uploads (expires_at);

CREATE TABLE deployment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    source_sha VARCHAR(64) NOT NULL,
    source_commit_message TEXT,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    requested_by BIGINT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    variables_snapshot JSONB,
    scaling_snapshot JSONB,
    requested_deployment_strategy VARCHAR(32),
    deployment_strategy VARCHAR(32),
    source_deployment_request_id BIGINT,
    cancel_requested_at TIMESTAMP WITH TIME ZONE,
    service_upload_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_requests PRIMARY KEY (id),
    CONSTRAINT ck_deployment_requests_environment CHECK (environment IN ('prod')),
    CONSTRAINT ck_deployment_requests_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR', 'VARIABLES_INVALID', 'DEPENDENCY_FAILED')),
    CONSTRAINT ck_deployment_requests_deployment_status CHECK (status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT ck_deployment_requests_requested_deployment_strategy CHECK (requested_deployment_strategy IN ('ROLLING', 'CANARY', 'BLUE_GREEN')),
    CONSTRAINT ck_deployment_requests_deployment_strategy CHECK (deployment_strategy IN ('ROLLING', 'CANARY', 'BLUE_GREEN')),
    CONSTRAINT ck_deployment_requests_deployment_trigger CHECK (trigger_type IN ('MANUAL', 'PUSH', 'CLI', 'REDEPLOY', 'ROLLBACK', 'RESTART', 'REMOVE')),
    CONSTRAINT fk_deployment_requests_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT fk_deployment_requests_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_deployment_requests_service_upload_id_service_uploads FOREIGN KEY(service_upload_id) REFERENCES service_uploads (id),
    CONSTRAINT fk_deployment_requests_source_deployment_request_id FOREIGN KEY(source_deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT uq_deployment_requests_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT uq_deployment_requests_service_upload_id UNIQUE (service_upload_id)
);

CREATE INDEX ix_deployment_requests_service_id_created_at ON deployment_requests (service_id, created_at);

CREATE UNIQUE INDEX uq_deployment_requests_active ON deployment_requests (service_id, environment) WHERE status IN ('QUEUED', 'BUILDING', 'DEPLOYING');

CREATE TABLE builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    builder VARCHAR(32),
    source_sha VARCHAR(64),
    codebuild_build_id VARCHAR(255),
    attempt INTEGER DEFAULT 1 NOT NULL,
    image_repository VARCHAR(500),
    image_tag VARCHAR(128),
    image_digest VARCHAR(80),
    deploy_config JSONB,
    failure_code VARCHAR(32),
    log_url TEXT,
    log_tail JSONB,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_builds PRIMARY KEY (id),
    CONSTRAINT ck_builds_build_status CHECK (status IN ('PENDING', 'SNAPSHOTTING', 'BUILDING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT ck_builds_builder CHECK (builder IN ('dockerfile', 'railpack')),
    CONSTRAINT ck_builds_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR', 'VARIABLES_INVALID', 'DEPENDENCY_FAILED')),
    CONSTRAINT fk_builds_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT uq_builds_codebuild_build_id UNIQUE (codebuild_build_id),
    CONSTRAINT uq_builds_deployment_request_id UNIQUE (deployment_request_id)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    priority INTEGER DEFAULT 0 NOT NULL,
    run_after TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    attempts INTEGER DEFAULT 0 NOT NULL,
    max_attempts INTEGER DEFAULT 5 NOT NULL,
    locked_by VARCHAR(255),
    locked_until TIMESTAMP WITH TIME ZONE,
    external_id VARCHAR(255),
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT ck_jobs_job_kind CHECK (kind IN ('BUILD', 'DEPLOY', 'RECONCILE', 'ROLLBACK', 'REMOVE')),
    CONSTRAINT ck_jobs_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'RETRY_WAIT', 'FAILED', 'MANUAL_INTERVENTION')),
    CONSTRAINT fk_jobs_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id)
);

CREATE INDEX ix_jobs_deployment_request_id ON jobs (deployment_request_id);

CREATE INDEX ix_jobs_queued ON jobs (priority DESC, created_at) WHERE status = 'QUEUED';

-- Worker 깨우기: job 생성, RUNNING → QUEUED·RETRY_WAIT, BUILD 종료 때 commit 시점에 NOTIFY jobs, <kind>.
CREATE FUNCTION notify_job_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('jobs', NEW.kind);
    RETURN NULL;
END $$;

CREATE TRIGGER trg_jobs_notify_insert AFTER INSERT ON jobs
    FOR EACH ROW EXECUTE FUNCTION notify_job_change();

CREATE TRIGGER trg_jobs_notify_release AFTER UPDATE OF status ON jobs
    FOR EACH ROW WHEN (OLD.status = 'RUNNING'
        AND (NEW.status IN ('QUEUED', 'RETRY_WAIT') OR NEW.kind = 'BUILD'))
    EXECUTE FUNCTION notify_job_change();

CREATE TABLE releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    build_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    image_digest VARCHAR(80) NOT NULL,
    gitops_commit_sha VARCHAR(64),
    revert_commit_sha VARCHAR(64),
    argo_sync_status VARCHAR(32),
    argo_health_status VARCHAR(32),
    previous_good_release_id BIGINT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    deadline_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_releases PRIMARY KEY (id),
    CONSTRAINT ck_releases_environment CHECK (environment IN ('prod')),
    CONSTRAINT ck_releases_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR', 'VARIABLES_INVALID', 'DEPENDENCY_FAILED')),
    CONSTRAINT ck_releases_release_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'ROLLING_BACK', 'ROLLED_BACK')),
    CONSTRAINT fk_releases_build_id_builds FOREIGN KEY(build_id) REFERENCES builds (id),
    CONSTRAINT fk_releases_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_releases_previous_good_release_id_releases FOREIGN KEY(previous_good_release_id) REFERENCES releases (id),
    CONSTRAINT fk_releases_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_releases_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id)
);

CREATE INDEX ix_releases_deployment_request_id ON releases (deployment_request_id);

CREATE INDEX ix_releases_last_known_good ON releases (service_id, environment, target_id, status);

CREATE UNIQUE INDEX uq_releases_service_id_target_id_in_flight ON releases (service_id, target_id) WHERE status IN ('PENDING', 'ROLLING_BACK');

CREATE TABLE deployment_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_status_histories PRIMARY KEY (id),
    CONSTRAINT ck_deployment_status_histories_failure_code CHECK (failure_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'BUILD_TIMED_OUT', 'BUILD_INFRA_ERROR', 'DEPLOY_FAILED', 'DEPLOY_TIMED_OUT', 'DEPLOY_INFRA_ERROR', 'VARIABLES_INVALID', 'DEPENDENCY_FAILED')),
    CONSTRAINT ck_deployment_status_histories_from_status CHECK (from_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT ck_deployment_status_histories_to_status CHECK (to_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION', 'SUPERSEDED')),
    CONSTRAINT fk_deployment_status_histories_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id)
);

CREATE INDEX ix_deployment_status_histories_deployment_request_id_created_at ON deployment_status_histories (deployment_request_id, created_at);

CREATE TABLE service_variables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    key VARCHAR(128) NOT NULL,
    encrypted_value TEXT,
    -- 참조 변수 {serviceId, property, scheme?, suffix?}. 값과 참조 중 하나만 있다.
    reference JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_variables PRIMARY KEY (id),
    CONSTRAINT ck_service_variables_value_or_reference CHECK ((encrypted_value IS NULL) <> (reference IS NULL)),
    CONSTRAINT fk_service_variables_service_id_services FOREIGN KEY(service_id) REFERENCES services (id)
);

CREATE UNIQUE INDEX uq_service_variables_service_id_key ON service_variables (service_id, key);

CREATE TABLE cli_login_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    poll_secret_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    user_id BIGINT,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    last_polled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_cli_login_sessions PRIMARY KEY (id),
    CONSTRAINT ck_cli_login_sessions_cli_login_session_status CHECK (status IN ('PENDING', 'APPROVED', 'DENIED', 'EXPIRED')),
    CONSTRAINT fk_cli_login_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id),
    CONSTRAINT uq_cli_login_sessions_public_id UNIQUE (public_id)
);

CREATE INDEX ix_cli_login_sessions_expires_at ON cli_login_sessions (expires_at);

CREATE TABLE deployment_diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    requested_by BIGINT,
    status VARCHAR(32) NOT NULL,
    result JSONB,
    error_code VARCHAR(64),
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_diagnoses PRIMARY KEY (id),
    CONSTRAINT ck_deployment_diagnoses_diagnosis_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT fk_deployment_diagnoses_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_deployment_diagnoses_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id)
);

CREATE INDEX ix_deployment_diagnoses_deployment_request_id_created_at ON deployment_diagnoses (deployment_request_id, created_at);

CREATE UNIQUE INDEX uq_deployment_diagnoses_deployment_request_id_running ON deployment_diagnoses (deployment_request_id) WHERE status = 'RUNNING';


CREATE TABLE deployment_repairs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    deployment_request_id BIGINT NOT NULL,
    diagnosis_id BIGINT NOT NULL,
    requested_by BIGINT,
    idempotency_key VARCHAR(128) NOT NULL,
    input_digest VARCHAR(64) NOT NULL,
    source_sha VARCHAR(40) NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    root_directory VARCHAR(255) NOT NULL,
    plan_ids JSONB NOT NULL,
    diagnosis_result JSONB NOT NULL,
    request_metadata JSONB NOT NULL,
    status VARCHAR(32) NOT NULL,
    result JSONB,
    error_code VARCHAR(64),
    deadline_at TIMESTAMP WITH TIME ZONE NOT NULL,
    generation_started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_repairs PRIMARY KEY (id),
    CONSTRAINT ck_deployment_repairs_repair_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN_OUTCOME')),
    CONSTRAINT fk_deployment_repairs_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_deployment_repairs_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_deployment_repairs_diagnosis_id_deployment_diagnoses FOREIGN KEY(diagnosis_id) REFERENCES deployment_diagnoses (id),
    CONSTRAINT fk_deployment_repairs_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id)
);

CREATE UNIQUE INDEX uq_deployment_repairs_deployment_request_id_running ON deployment_repairs (deployment_request_id) WHERE status = 'RUNNING';

CREATE UNIQUE INDEX uq_deployment_repairs_service_id_idempotency_key ON deployment_repairs (service_id, idempotency_key);

CREATE TABLE onprem_servers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(63) NOT NULL,
    server_key VARCHAR(8) NOT NULL,
    target_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    registration_token_hash VARCHAR(64) NOT NULL,
    registration_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    tailnet_fqdn VARCHAR(255),
    api_ca_cert TEXT,
    encrypted_service_account_token TEXT,
    sealed_secrets_cert TEXT,
    server_secret_hash VARCHAR(64),
    connect_generation INTEGER DEFAULT 0 NOT NULL,
    gitops_commit_sha VARCHAR(40),
    gitops_attempts INTEGER DEFAULT 0 NOT NULL,
    connect_deadline_at TIMESTAMP WITH TIME ZONE,
    connected_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    next_check_at TIMESTAMP WITH TIME ZONE,
    locked_by VARCHAR(255),
    locked_until TIMESTAMP WITH TIME ZONE,
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_onprem_servers PRIMARY KEY (id),
    CONSTRAINT ck_onprem_servers_onprem_server_status CHECK (status IN ('PENDING', 'REGISTERING', 'CONNECTED', 'FAILED')),
    CONSTRAINT ck_onprem_servers_onprem_server_failure_code CHECK (failure_code IN ('CONNECT_TIMED_OUT', 'GITOPS_COMMIT_FAILED')),
    CONSTRAINT fk_onprem_servers_owner_id_users FOREIGN KEY(owner_id) REFERENCES users (id),
    CONSTRAINT fk_onprem_servers_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id),
    CONSTRAINT uq_onprem_servers_registration_token_hash UNIQUE (registration_token_hash),
    CONSTRAINT uq_onprem_servers_server_key UNIQUE (server_key),
    CONSTRAINT uq_onprem_servers_server_secret_hash UNIQUE (server_secret_hash),
    CONSTRAINT uq_onprem_servers_target_id UNIQUE (target_id)
);

CREATE INDEX ix_onprem_servers_next_check_at ON onprem_servers (next_check_at) WHERE next_check_at IS NOT NULL;

CREATE UNIQUE INDEX uq_onprem_servers_owner_id_name ON onprem_servers (owner_id, name) WHERE NOT is_deleted;

-- 서비스를 만들기 전 레포 구성 분석(Analysis Gate) 1건. Build Worker 가 QUEUED·lease 만료 RUNNING 을
-- FOR UPDATE SKIP LOCKED 로 선점한다. result 는 분석기 응답(iris.analysis-gate.v1) 원문이다.
CREATE TABLE repository_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    github_installation_id BIGINT,
    source_branch VARCHAR(255) NOT NULL,
    source_sha VARCHAR(64),
    root_directory VARCHAR(255),
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) DEFAULT 'QUEUED' NOT NULL,
    decision VARCHAR(32),
    complexity VARCHAR(32),
    result JSONB,
    error_code VARCHAR(32),
    error_message TEXT,
    applied_service_ids JSONB,
    attempts INTEGER DEFAULT 0 NOT NULL,
    locked_by VARCHAR(255),
    locked_until TIMESTAMP WITH TIME ZONE,
    -- 푸시로 다시 접수한 스택 재분석의 스택. 외래 키는 service_stacks 를 만든 뒤 단다.
    stack_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_repository_analyses PRIMARY KEY (id),
    CONSTRAINT ck_repository_analyses_mode CHECK (mode IN ('auto', 'force')),
    CONSTRAINT ck_repository_analyses_repository_analysis_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'APPLIED')),
    CONSTRAINT ck_repository_analyses_decision CHECK (decision IN ('skip', 'analyze')),
    CONSTRAINT ck_repository_analyses_complexity CHECK (complexity IN ('simple', 'complex', 'unsupported')),
    CONSTRAINT ck_repository_analyses_error_code CHECK (error_code IN ('SOURCE_NOT_ACCESSIBLE', 'SOURCE_REF_NOT_FOUND', 'SOURCE_TOO_LARGE', 'SOURCE_INVALID', 'ANALYZER_UNAVAILABLE', 'ANALYZER_TIMED_OUT', 'ANALYZER_FAILED', 'ANALYSIS_INTERRUPTED')),
    CONSTRAINT fk_repository_analyses_github_installation_id_github_in_d95f FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_repository_analyses_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id),
    CONSTRAINT fk_repository_analyses_user_id_users FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_repository_analyses_pending ON repository_analyses (created_at) WHERE status IN ('QUEUED', 'RUNNING');

CREATE INDEX ix_repository_analyses_project_id ON repository_analyses (project_id);

CREATE INDEX ix_repository_analyses_user_id ON repository_analyses (user_id);

CREATE UNIQUE INDEX uq_repository_analyses_stack_id_source_sha ON repository_analyses (stack_id, source_sha) WHERE stack_id IS NOT NULL;

-- Worker 깨우기: 분석 접수, 종료 신호로 반납(RUNNING → QUEUED) 때 commit 시점에 NOTIFY jobs, REPOSITORY_ANALYSIS.
CREATE FUNCTION notify_repository_analysis_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('jobs', 'REPOSITORY_ANALYSIS');
    RETURN NULL;
END $$;

CREATE TRIGGER trg_repository_analyses_notify_insert AFTER INSERT ON repository_analyses
    FOR EACH ROW EXECUTE FUNCTION notify_repository_analysis_change();

CREATE TRIGGER trg_repository_analyses_notify_release AFTER UPDATE OF status ON repository_analyses
    FOR EACH ROW WHEN (OLD.status = 'RUNNING' AND NEW.status = 'QUEUED')
    EXECUTE FUNCTION notify_repository_analysis_change();

-- 같은 레포(저장소·브랜치·위치) 분석에서 만든 서비스(앱 + 관리형 DB) 묶음. analysis_id 는 기준 분석.
CREATE TABLE service_stacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    source_branch VARCHAR(255) NOT NULL,
    root_directory VARCHAR(255),
    github_installation_id BIGINT,
    analysis_id BIGINT NOT NULL,
    -- {analysisId, sourceSha, detectedAt, changes: [{type, unitId, field?, from?, to?}]}
    pending_changes JSONB,
    pending_analysis_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_stacks PRIMARY KEY (id),
    CONSTRAINT fk_service_stacks_analysis_id_repository_analyses FOREIGN KEY(analysis_id) REFERENCES repository_analyses (id),
    CONSTRAINT fk_service_stacks_github_installation_id_github_installations FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT fk_service_stacks_pending_analysis_id_repository_analyses FOREIGN KEY(pending_analysis_id) REFERENCES repository_analyses (id),
    CONSTRAINT fk_service_stacks_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id)
);

CREATE INDEX ix_service_stacks_project_id ON service_stacks (project_id);

CREATE INDEX ix_service_stacks_repository ON service_stacks (source_repository_url, source_branch);

ALTER TABLE services ADD CONSTRAINT fk_services_stack_id_service_stacks FOREIGN KEY(stack_id) REFERENCES service_stacks (id);

ALTER TABLE repository_analyses ADD CONSTRAINT fk_repository_analyses_stack_id_service_stacks FOREIGN KEY(stack_id) REFERENCES service_stacks (id);

-- 스택 서비스를 의존 순서대로 배포하는 1회. 서비스마다 배포 요청을 하나씩 만든다.
CREATE TABLE stack_deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stack_id BIGINT NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    requested_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_stack_deployments PRIMARY KEY (id),
    CONSTRAINT ck_stack_deployments_deployment_trigger CHECK (trigger_type IN ('MANUAL', 'PUSH', 'CLI', 'REDEPLOY', 'ROLLBACK', 'RESTART', 'REMOVE')),
    CONSTRAINT fk_stack_deployments_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT fk_stack_deployments_stack_id_service_stacks FOREIGN KEY(stack_id) REFERENCES service_stacks (id),
    CONSTRAINT uq_stack_deployments_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX ix_stack_deployments_stack_id ON stack_deployments (stack_id);

-- 스택 배포의 서비스 한 단계. WAITING 은 앞 단계(depends_on_deployment_request_ids)가 모두 SUCCEEDED 가
-- 되면 첫 job 을 만들어 STARTED, 앞 단계가 실패하면 HELD(요청은 FAILED · DEPENDENCY_FAILED).
CREATE TABLE stack_deployment_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stack_deployment_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    deployment_request_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    depends_on_deployment_request_ids JSONB DEFAULT '[]'::jsonb NOT NULL,
    status VARCHAR(32) NOT NULL,
    held_by_deployment_request_id BIGINT,
    started_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_stack_deployment_steps PRIMARY KEY (id),
    CONSTRAINT ck_stack_deployment_steps_stack_deployment_step_status CHECK (status IN ('WAITING', 'STARTED', 'HELD')),
    CONSTRAINT fk_stack_deployment_steps_deployment_request_id_deploym_18c1 FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_stack_deployment_steps_held_by_deployment_request_id_6215 FOREIGN KEY(held_by_deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_stack_deployment_steps_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_stack_deployment_steps_stack_deployment_id_stack_deployments FOREIGN KEY(stack_deployment_id) REFERENCES stack_deployments (id),
    CONSTRAINT uq_stack_deployment_steps_deployment_request_id UNIQUE (deployment_request_id)
);

CREATE INDEX ix_stack_deployment_steps_stack_deployment_id ON stack_deployment_steps (stack_deployment_id);

-- 관리형 DB 초기화 스크립트 내용(/docker-entrypoint-initdb.d). sha256 으로 찾고 같은 내용은 한 번만 둔다.
-- 분석 결과 dependencies[].initScripts 와 services.database_config.initScripts 가 sha256 으로 가리킨다.
CREATE TABLE database_init_scripts (
    sha256 VARCHAR(64) NOT NULL,
    size_bytes INTEGER NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_database_init_scripts PRIMARY KEY (sha256),
    CONSTRAINT ck_database_init_scripts_content_size CHECK (octet_length(content) = size_bytes),
    CONSTRAINT ck_database_init_scripts_size_bytes CHECK (size_bytes >= 0 AND size_bytes <= 1048576)
);

-- 서비스 콘솔(Pod 셸) 연결 ticket 발급 감사 기록. 쓰기만 하고 고치지 않으며 지우지 않는다(ADR 0033).
CREATE TABLE console_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    release_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_console_sessions PRIMARY KEY (id),
    CONSTRAINT fk_console_sessions_release_id_releases FOREIGN KEY(release_id) REFERENCES releases (id),
    CONSTRAINT fk_console_sessions_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_console_sessions_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id),
    CONSTRAINT fk_console_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id),
    CONSTRAINT uq_console_sessions_public_id UNIQUE (public_id)
);

CREATE INDEX ix_console_sessions_service_id_created_at ON console_sessions (service_id, created_at);

CREATE TABLE onprem_metric_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    pod VARCHAR(253) NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cpu_millicores DOUBLE PRECISION NOT NULL,
    memory_bytes BIGINT NOT NULL,
    CONSTRAINT pk_onprem_metric_samples PRIMARY KEY (id),
    CONSTRAINT fk_onprem_metric_samples_service_id_services FOREIGN KEY(service_id) REFERENCES services (id)
);

CREATE INDEX ix_onprem_metric_samples_collected_at ON onprem_metric_samples (collected_at);

CREATE INDEX ix_onprem_metric_samples_service_id_collected_at ON onprem_metric_samples (service_id, collected_at);
