-- 물리 DB 스키마(DDL) 단일 출처 — PostgreSQL.
-- app/models/*.py, alembic/versions/ 와 일치시킨다 (.claude/rules/db-migration.md).
-- 2026-10-02: 분석 파이프라인·실패 진단 작업과 Build/Release 실행 식별자 추가.

CREATE TABLE github_installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    installation_id BIGINT NOT NULL,
    account_login VARCHAR(255) NOT NULL,
    account_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_github_installations PRIMARY KEY (id),
    CONSTRAINT uq_github_installations_installation_id UNIQUE (installation_id)
);

CREATE TABLE targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(64) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    region VARCHAR(32),
    domain_suffix VARCHAR(255),
    cluster_ref VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_targets PRIMARY KEY (id),
    CONSTRAINT uq_targets_name UNIQUE (name),
    CONSTRAINT ck_targets_target_kind CHECK (kind IN ('AWS', 'LOCAL'))
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    github_id BIGINT NOT NULL,
    login VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_github_id UNIQUE (github_id)
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_owner_id_users FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE INDEX ix_projects_owner_id ON projects (owner_id);

CREATE UNIQUE INDEX uq_projects_owner_id_name ON projects (owner_id, name) WHERE NOT is_deleted;

CREATE TABLE user_github_installations (
    user_id BIGINT NOT NULL,
    github_installation_id BIGINT NOT NULL,
    CONSTRAINT pk_user_github_installations PRIMARY KEY (user_id, github_installation_id),
    CONSTRAINT fk_user_github_installations_user_id_users FOREIGN KEY(user_id) REFERENCES users (id),
    CONSTRAINT fk_user_github_installations_github_installation_id_git_2fda FOREIGN KEY(github_installation_id) REFERENCES github_installations (id)
);

CREATE TABLE services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    github_installation_id BIGINT NOT NULL,
    source_branch VARCHAR(255) NOT NULL,
    root_directory VARCHAR(255),
    is_auto_deploy BOOLEAN DEFAULT true NOT NULL,
    builder VARCHAR(32),
    dockerfile_path VARCHAR(255),
    platform VARCHAR(32) DEFAULT 'linux/amd64' NOT NULL,
    railpack_version VARCHAR(32),
    analysis_plan JSONB,
    port INTEGER,
    build_command TEXT,
    start_command TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    is_deleted BOOLEAN DEFAULT false NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT fk_services_project_id_projects FOREIGN KEY(project_id) REFERENCES projects (id),
    CONSTRAINT fk_services_github_installation_id_github_installations FOREIGN KEY(github_installation_id) REFERENCES github_installations (id),
    CONSTRAINT ck_services_builder CHECK (builder IN ('dockerfile', 'railpack'))
);

CREATE INDEX ix_services_github_installation_id ON services (github_installation_id);

CREATE INDEX ix_services_project_id ON services (project_id);

CREATE UNIQUE INDEX uq_services_project_id_name ON services (project_id, name) WHERE NOT is_deleted;

CREATE TABLE deployment_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    source_sha VARCHAR(64) NOT NULL,
    source_commit_message TEXT,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    requested_by BIGINT,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    variables_snapshot JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_requests PRIMARY KEY (id),
    CONSTRAINT fk_deployment_requests_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT ck_deployment_requests_environment CHECK (environment IN ('prod')),
    CONSTRAINT ck_deployment_requests_deployment_trigger CHECK (trigger_type IN ('MANUAL', 'PUSH', 'CLI', 'REDEPLOY', 'ROLLBACK')),
    CONSTRAINT uq_deployment_requests_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_deployment_requests_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT ck_deployment_requests_deployment_status CHECK (status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION')),
    CONSTRAINT ck_deployment_requests_failure_code CHECK (failure_code IN ('BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'DEPLOY_FAILED'))
);

CREATE INDEX ix_deployment_requests_service_id_created_at ON deployment_requests (service_id, created_at);

CREATE UNIQUE INDEX uq_deployment_requests_active ON deployment_requests (service_id, environment) WHERE status IN ('QUEUED', 'BUILDING', 'DEPLOYING');

CREATE TABLE service_analyses (
    id VARCHAR(36) NOT NULL,
    service_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    source_branch VARCHAR(255) NOT NULL,
    source_sha VARCHAR(40) NOT NULL,
    root_directory VARCHAR(255) NOT NULL,
    github_installation_id BIGINT NOT NULL,
    mode VARCHAR(12) NOT NULL,
    model_selection JSONB,
    status VARCHAR(32) DEFAULT 'QUEUED' NOT NULL,
    stage VARCHAR(64) DEFAULT 'queued' NOT NULL,
    source_snapshot_id VARCHAR(128),
    context_hash VARCHAR(128),
    result_digest VARCHAR(128),
    analysis_status VARCHAR(32),
    analysis_result JSONB,
    verification_report JSONB,
    source_readiness JSONB,
    deployment_dossier JSONB,
    run_report JSONB,
    evidence JSONB,
    builder_recommendation VARCHAR(32),
    review_required BOOLEAN DEFAULT true NOT NULL,
    error_code VARCHAR(64),
    attempts INTEGER DEFAULT 0 NOT NULL,
    lease_token VARCHAR(36),
    locked_until TIMESTAMP WITH TIME ZONE,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    selected_service_candidate_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_service_analyses PRIMARY KEY (id),
    CONSTRAINT fk_service_analyses_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_analyses_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT ck_service_analyses_analysis_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX ix_service_analyses_latest ON service_analyses (service_id, created_at DESC);

CREATE INDEX ix_service_analyses_queue ON service_analyses (status, locked_until);

CREATE UNIQUE INDEX uq_service_analyses_active ON service_analyses (service_id) WHERE status IN ('QUEUED', 'RUNNING');

CREATE TABLE service_targets (
    service_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    CONSTRAINT pk_service_targets PRIMARY KEY (service_id, target_id),
    CONSTRAINT fk_service_targets_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_service_targets_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id)
);

CREATE INDEX ix_service_targets_target_id ON service_targets (target_id);

CREATE TABLE builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    builder VARCHAR(32) NOT NULL,
    codebuild_build_id VARCHAR(255),
    image_repository VARCHAR(500),
    image_digest VARCHAR(80),
    log_url TEXT,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    source_sha VARCHAR(64),
    source_archive_digest VARCHAR(80),
    source_snapshot_key TEXT,
    build_config JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_builds PRIMARY KEY (id),
    CONSTRAINT uq_builds_deployment_request_id UNIQUE (deployment_request_id),
    CONSTRAINT fk_builds_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT ck_builds_builder CHECK (builder IN ('dockerfile', 'railpack')),
    CONSTRAINT uq_builds_codebuild_build_id UNIQUE (codebuild_build_id)
);

CREATE TABLE deployment_diagnoses (
    id VARCHAR(36) NOT NULL,
    service_id BIGINT NOT NULL,
    deployment_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    attempt_id VARCHAR(128) NOT NULL,
    trigger VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    model_selection JSONB,
    deployment_context JSONB NOT NULL,
    source_logs JSONB,
    result JSONB,
    error_code VARCHAR(64),
    attempts INTEGER DEFAULT 0 NOT NULL,
    lease_token VARCHAR(36),
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_diagnoses PRIMARY KEY (id),
    CONSTRAINT uq_deployment_diagnoses_attempt UNIQUE (deployment_id, attempt_id),
    CONSTRAINT fk_deployment_diagnoses_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_deployment_diagnoses_deployment_id_deployment_requests FOREIGN KEY(deployment_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_deployment_diagnoses_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT ck_deployment_diagnoses_diagnosis_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT'))
);

CREATE INDEX ix_deployment_diagnoses_latest ON deployment_diagnoses (deployment_id, created_at DESC);

CREATE INDEX ix_deployment_diagnoses_queue ON deployment_diagnoses (status, locked_until);

CREATE TABLE deployment_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(32),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_deployment_status_histories PRIMARY KEY (id),
    CONSTRAINT fk_deployment_status_histories_deployment_request_id_de_b8ce FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT ck_deployment_status_histories_from_status CHECK (from_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION')),
    CONSTRAINT ck_deployment_status_histories_to_status CHECK (to_status IN ('QUEUED', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK', 'MANUAL_INTERVENTION')),
    CONSTRAINT ck_deployment_status_histories_failure_code CHECK (failure_code IN ('BUILD_CONFIG_REQUIRED', 'BUILD_FAILED', 'DEPLOY_FAILED'))
);

CREATE INDEX ix_deployment_status_histories_deployment_request_id_created_at ON deployment_status_histories (deployment_request_id, created_at);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    payload JSONB DEFAULT '{}'::jsonb NOT NULL,
    priority INTEGER DEFAULT 0 NOT NULL,
    run_after TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    attempts INTEGER DEFAULT 0 NOT NULL,
    max_attempts INTEGER DEFAULT 5 NOT NULL,
    locked_by VARCHAR(255),
    locked_until TIMESTAMP WITH TIME ZONE,
    external_id VARCHAR(255),
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_jobs PRIMARY KEY (id),
    CONSTRAINT fk_jobs_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT ck_jobs_job_kind CHECK (kind IN ('BUILD', 'DEPLOY', 'RECONCILE', 'ROLLBACK')),
    CONSTRAINT ck_jobs_job_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'RETRY_WAIT', 'FAILED', 'MANUAL_INTERVENTION'))
);

CREATE INDEX ix_jobs_deployment_request_id ON jobs (deployment_request_id);

CREATE INDEX ix_jobs_queued ON jobs (priority DESC, created_at) WHERE status = 'QUEUED';

CREATE TABLE pipeline_runs (
    id VARCHAR(36) NOT NULL,
    service_id BIGINT NOT NULL,
    requested_by BIGINT NOT NULL,
    source_repository_url VARCHAR(500) NOT NULL,
    source_branch VARCHAR(255) NOT NULL,
    source_sha VARCHAR(40) NOT NULL,
    root_directory VARCHAR(255) NOT NULL,
    github_installation_id BIGINT NOT NULL,
    mode VARCHAR(12) NOT NULL,
    trigger_type VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    auto_deploy BOOLEAN NOT NULL,
    enable_auto_deploy BOOLEAN NOT NULL,
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(64) NOT NULL,
    analysis_id VARCHAR(36),
    deployment_request_id BIGINT,
    config_snapshot JSONB NOT NULL,
    target_ids JSONB NOT NULL,
    confirmed_inputs JSONB NOT NULL,
    questions JSONB NOT NULL,
    deployment_dossier JSONB,
    planning_report JSONB,
    execution_plan JSONB,
    plan_digest VARCHAR(64),
    model_selection JSONB,
    error_code VARCHAR(64),
    attempts INTEGER DEFAULT 0 NOT NULL,
    lease_token VARCHAR(36),
    locked_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_pipeline_runs PRIMARY KEY (id),
    CONSTRAINT fk_pipeline_runs_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT fk_pipeline_runs_requested_by_users FOREIGN KEY(requested_by) REFERENCES users (id),
    CONSTRAINT ck_pipeline_runs_deployment_trigger CHECK (trigger_type IN ('MANUAL', 'PUSH', 'CLI', 'REDEPLOY', 'ROLLBACK')),
    CONSTRAINT uq_pipeline_runs_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_pipeline_runs_pipeline_status CHECK (status IN ('QUEUED', 'ANALYZING', 'AWAITING_INPUT', 'PLANNING', 'BUILDING', 'DEPLOYING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    CONSTRAINT fk_pipeline_runs_analysis_id_service_analyses FOREIGN KEY(analysis_id) REFERENCES service_analyses (id),
    CONSTRAINT fk_pipeline_runs_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id)
);

CREATE INDEX ix_pipeline_runs_latest ON pipeline_runs (service_id, created_at DESC);

CREATE INDEX ix_pipeline_runs_queue ON pipeline_runs (status, locked_until);

CREATE UNIQUE INDEX uq_pipeline_runs_active ON pipeline_runs (service_id) WHERE status IN ('ANALYZING','AWAITING_INPUT','PLANNING','BUILDING','DEPLOYING');

CREATE TABLE releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deployment_request_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    environment VARCHAR(32) NOT NULL,
    target_id BIGINT NOT NULL,
    image_digest VARCHAR(80) NOT NULL,
    gitops_commit_sha VARCHAR(64),
    image_repository VARCHAR(500),
    revert_commit_sha VARCHAR(64),
    deadline_at TIMESTAMP WITH TIME ZONE,
    argo_sync_status VARCHAR(32),
    argo_health_status VARCHAR(32),
    previous_good_release_id BIGINT,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_releases PRIMARY KEY (id),
    CONSTRAINT fk_releases_deployment_request_id_deployment_requests FOREIGN KEY(deployment_request_id) REFERENCES deployment_requests (id),
    CONSTRAINT fk_releases_service_id_services FOREIGN KEY(service_id) REFERENCES services (id),
    CONSTRAINT ck_releases_environment CHECK (environment IN ('prod')),
    CONSTRAINT fk_releases_target_id_targets FOREIGN KEY(target_id) REFERENCES targets (id),
    CONSTRAINT fk_releases_previous_good_release_id_releases FOREIGN KEY(previous_good_release_id) REFERENCES releases (id),
    CONSTRAINT ck_releases_release_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'ROLLED_BACK'))
);

CREATE INDEX ix_releases_deployment_request_id ON releases (deployment_request_id);

CREATE INDEX ix_releases_last_known_good ON releases (service_id, environment, target_id, status);
